"""
JSON-RPC ID type aliases and validators for the Alchemist protocol.

- ClientRequestId: UUID string, generated by the NeoVim client.
- ServerRequestId: ``srv_req_<suffix>`` string, generated by the daemon.
- JsonRpcId: union of the two.
"""
from __future__ import annotations

import re
import uuid
from typing import Union

# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

ClientRequestId = str  # validated UUID string
ServerRequestId = str  # validated srv_req_* string
JsonRpcId = Union[ClientRequestId, ServerRequestId]

# ---------------------------------------------------------------------------
# Regexes
# ---------------------------------------------------------------------------

_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)
_SRV_REQ_RE = re.compile(r"^srv_req_")


# ---------------------------------------------------------------------------
# Validators
# ---------------------------------------------------------------------------

def is_client_request_id(id_: str) -> bool:
    """Return True if id_ is a valid UUID-format client request ID."""
    return bool(_UUID_RE.match(id_))


def is_server_request_id(id_: str) -> bool:
    """Return True if id_ is a valid server-request ID (srv_req_*)."""
    return bool(_SRV_REQ_RE.match(id_))


def validate_client_request_id(id_: str) -> ClientRequestId:
    """Raise ValueError if id_ is not a valid client request ID."""
    if not is_client_request_id(id_):
        raise ValueError(f"Not a valid client request ID (expected UUID): {id_!r}")
    return id_


def validate_server_request_id(id_: str) -> ServerRequestId:
    """Raise ValueError if id_ is not a valid server request ID."""
    if not is_server_request_id(id_):
        raise ValueError(
            f"Not a valid server request ID (expected srv_req_*): {id_!r}"
        )
    return id_


# ---------------------------------------------------------------------------
# Factories
# ---------------------------------------------------------------------------

def make_client_request_id() -> ClientRequestId:
    """Generate a fresh UUID client request ID."""
    return str(uuid.uuid4())


def make_server_request_id(suffix: str) -> ServerRequestId:
    """Create a server request ID from an arbitrary suffix."""
    return f"srv_req_{suffix}"
